### ISSUE TITLE
Create UperTuner Documentation

### ISSUE THREAD

**Issue by jherrmann06** [frc1675/frc1675-2024-general#24]
# Task Description
Write a document explaining how to use UperTuner.

## Prerequisites
None

## Actions Needed
UperTuner document should include: 
* Installation instructions
* Usage in code
* Usage on the dashboard
* What will happen during competitions

## Completion Criteria
- [ ] UperTuner document is completed and includes all above sections
- [ ] UperTuner JAR is uploaded to this repo for easy access
- [ ] UperTuner document is approved and merged.

**Comment by jherrmann06** [comment]
I don't think we will actually be using UperTuner in any of the other subsystems this year. This could be a good postseason project but we don't need to work on it right now.
